### ISSUE TITLE
DCO Workflow management

### ISSUE THREAD

**Issue by santiagobernalg** [boa-project/boa-admin#15]
An DCO will go through a workflow which consists of the following states:
- On Hold: It indicates that the DCO has been created but has not been approved, hence, only its creator is visible, users with the capability to see all DCOT and other users who have been granted read permission.
- Published: The DCO is visible to all users with capability to view published DCOs.

**Comment by santiagobernalg** [comment]
This is all about DCO Management, what is the workflow if an object is then modified after published? what is the status before a new version is published?

**Comment by davidherney** [comment]
It is required define two possibilities by configuration :
The first one, all versions from a same object share the state
The second one, a user can change a public object and the new version require approval, the state is from the old version.
@jesusoterove Agree?

**Comment by jesusoterove** [comment]
We have the following states currently:
inprogress: Object created and metadata being edited. Not yet published.
ready: Object completed, ready to publish, but waiting for approval.
published: Object published
unpublished: Object logically removed. Only users already using the object will have access to it.

I guess we need to enhance this states to cover the whole workflow, or perhaps use a combination of version and state, so you can have version 1.0 published, but version 1.1 in progress. This will be compliant with the second option you mentioned.

@davidherney

**Comment by davidherney** [comment]
I think that this states cover the whole workflow.

I prefer use the combination of version and state like you mentioned. However, I think that is better if is selected by configurations: (option 1) all version has the same state AND (option 2) each version has different states.
