### ISSUE TITLE
 The unzip option does not work correctly

### ISSUE THREAD

**Issue by jmauro007** [boa-project/boa-admin#204]
When using the option to unzip a .zip file, initially it seems that unzip it, but when you try to enter the folder you can not see anything and the following error is observed in the server: 
 
Error while trying to open directory app.fs://a2180b09a541edfdcd78b2a2eebee975/path/to/folder/zip in /path/boa/admin/src/boa/plugins/access.fs/FsAccessDriver.class.php

**Comment by jmauro007** [comment]
@jesusoterove

**Comment by rstpv** [comment]
@jmauro007 Are you in the latest version of the sources?
There was a fix for zip explore: https://github.com/boa-project/boa-admin/pull/192

**Comment by davidherney** [comment]
Hi @rstpv 

I test it in the last version. The issue #192 is fine, the error is different. Now, the zip content is shown but it is not uncompressed correctly.

Saludos

**Comment by rstpv** [comment]
@davidherney how can I reproduce it?
Tried "Extract" and it worked. Where do I find the unzip option?
