### ISSUE TITLE
Dos errores en nombres de variables

### ISSUE THREAD

**Issue by davidherney** [boa-project/boa-admin#210]
La primera es la variables subject que debería ser $nodeName, en el archivo: src/boa/plugins/access.dco/DcoExplorer.class.php

```
- if (preg_match("/^\\.(:?.*)\\.manifest(:?\\.published)?$/", subject)) continue; //Skip manifest files
+ if (preg_match("/^\\.(:?.*)\\.manifest(:?\\.published)?$/", $nodeName)) continue; //Skip manifest files
```

La segunda es en el archivo src/boa/plugins/meta.lom/LomMetaManager.class.php que falta el signo $

```
- if (!itemsFound){
+ if (!$itemsFound){

```

**Comment by jesusoterove** [comment]
Issue fixed by PR #212 and #214
